<?php
$title = 'Удаление альбома';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Вы уверены, что хотите удалить альбом
    '<?php echo $this->escapeHtml($album->title); ?>'?
</p>
<?php
$url = $this->url('gallery', array(
    'action' => 'deleteAlbum',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $album->id; ?>" />
        <input type="submit" name="del" value="Yes"  />
        <input type="submit" name="del" value="No" />
    </div>
</form>