<?php
$title = 'Удаление фотографии';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<img src="../../upload/preview/<?=$picture->src;?>">
<p>Вы уверены, что хотите удалить
    '<?php echo $this->escapeHtml($picture->title); ?>'?
</p>
<?php
$url = $this->url('gallery', array(
    'action' => 'deletePicture',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $picture->id; ?>" />
        <input type="submit" name="del" value="Yes"  />
        <input type="submit" name="del" value="No" />
    </div>
</form>