<?php
$title = 'Редактирование альбома';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div id="gallery">
    <div class="add-album">
        <a href='<?=$this->url('gallery')?>'>Назад</a>
    </div>
    <div class="form">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url(
            'gallery',
            array(
                'action' => 'editAlbum',
                'id'     => $this->id,
            )
        ));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('id'));
        echo $this->formRow($form->get('title'));
        echo $this->formRow($form->get('description'));
        echo $this->formRow($form->get('author'));
        echo $this->formRow($form->get('mail'));
        echo $this->formRow($form->get('phone'));

        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
        ?>
    </div>
</div>